const dnaDataset = [
    // --- MANUSIA (HUMAN) ---
    { id: 1, organism: "Homo Sapiens", gene_name: "Insulin (INS)", sequence: "AGCCCTCCAGGACAGGCTGCATCAGAAGAGGCCATCAAGCAGGTCTGTTCCAAGGGCCTTTGCGTCAGGTGGGCTCAGGATTCCAGGGTGGCTGGACCCCAGGCCCCAGCTCTGCAGCAGGGAGGACGTGGCTGGGCTCGTGAAGCATGTGGGGGTGAGCCCAGGGGCCCCAAGGCAGGGCACCTGGCCTTCAGCCTGCCTCAGCCCTGC" },
    { id: 2, organism: "Homo Sapiens", gene_name: "Hemoglobin Beta (HBB)", sequence: "ACATTTGCTTCTGACACAACTGTGTTCACTAGCAACCTCAAACAGACACCATGGTGCATCTGACTCCTGAGGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGCAGGTTGGTATCAAGGTTACAAGACAGGTTTAAGGAGACCAATAGAAACTGGGCATGTGGAGACAGAGAAGACTCTTGGGTTTCT" },
    { id: 3, organism: "Homo Sapiens", gene_name: "TP53 (Tumor Suppressor)", sequence: "GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCA" },
    { id: 4, organism: "Homo Sapiens", gene_name: "BRCA1 (DNA Repair)", sequence: "GGCTTAAGAAACAAAGTAAAATATATAAACAAGAATATAAAAATTTATATATATACTTGTAAATATTTTCTGTAAATACTTATTTATAATAAAAATGAAAGTTTGAATCTTTCAAAATCTACACAGTTGCAAAATCACTTACTATAAAAATAAACCATTTTCAATATAGCACATTTTTATACATTTCCAAAGTTCAGGAACTTTTAGCAAA" },
    { id: 5, organism: "Homo Sapiens", gene_name: "MYH16 (Jaw Muscle)", sequence: "ATGTTTTCCTGGCTATATGCCTTAAACCTAAAAATATATTTTTAAAATTTTTTTTCTTTTTTTAGGATCTAGAACAGGCAGCTGAACAGGCAGCCAGGGCAAAGTCTGAAGCTGAAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCGGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCGGCAGCAGCAGCAG" },
    { id: 6, organism: "Homo Sapiens", gene_name: "ACE2 (Receptor)", sequence: "TTAATAAGAGTTTGATATCAGAGACTGAGAAGTCATTATTTTCTACAAGGGAAAATAAGTAACTGAGATTTCTATGTTTTGTTTTTCTTTTTTCTTTTTTTTTTTTTTTTTTTTGAGATGGAGTCTTGCTCTGTCGCCCAGGCTGGAGTGCAGTGGCGTGATCTCGGCTCACTGCAAGCTCCGCCTCCCGGGTTCACGCCATTCTCCTGCCTCAGCCT" },
    { id: 7, organism: "Homo Sapiens", gene_name: "Dopamine Receptor D4", sequence: "GCGGCGGGGGCAGGAGCGGGGCGCGGCGGGGGCAGGAGCGGGGCGCGGCGGGGGCAGGAGCGGGGCGCGGCGGGGGCAGGAGCGGGGCGCGGCGGGGGCAGGAGCGGGGCGCGGCGGGGGCAGGAGCGGGGCGCGGCGGGGGCAGGAGCGGGGCGCGGCGGGGGCAGGAGCGGGGCGCGGCGGGGGCAGGAGCGGGGCGCGGCGGGGGCAGGAGCGGGGC" },

    // --- VIRUS & PATHOGEN ---
    { id: 8, organism: "SARS-CoV-2", gene_name: "Spike Protein", sequence: "ATGTTTGTTTTTCTTGTTTTATTGCCACTAGTCTCTAGTCAGTGTGTTAATCTTACAACCAGAACTCAATTACCCCCTGCATACACTAATTCTTTCACACGTGGTGTTTATTACCCTGACAAAGTTTTCAGATCCTCAGTTTTACATTCAACTCAGGCTTGTTCTTTCCTTTGTTT" },
    { id: 9, organism: "Influenza A", gene_name: "Hemagglutinin (HA)", sequence: "ATGAAGGCAATACTAGTAGTTCTGCTATATACATTTGCAACCGCAAATGCAGACACATTATGTATAGGTTATCATGCGAACAATTCAACAGACACTGTAGACACAGTACTAGAAAAGAATGTAACAGTAACACACTCTGTTAACCTTCTAGAAGACAAGCATAACGGGAAACTATGCAAACTAAGAGGGGTAGCCCCATTGCATTTGGGTAAATGTAACATT" },
    { id: 10, organism: "Ebola Virus", gene_name: "Glycoprotein", sequence: "ATGCGCGCGTTTCCGGTTTATATCGAGATATCCTTAAACCCGGGAGCAATACATCGTTATATCTACAGTATGCGATGATATCCGATAGCTAGCTAGCTAGCTAGCTAGCTAGAGAGAGCTAGCTAGCTAGCTAGCGCTATATATATATCGAGCTAGCTAGCGCGCGCGATCGATCG" },
    { id: 11, organism: "HIV-1", gene_name: "Env (Envelope)", sequence: "AGAAAGAGCAGAAGACAGTGGCAATGAGAGTGATGGGGATCAGGAAGAATTATCAGCACTTGTGGAAATGGGGCACCATGCTCCTTGGGATGTTAATGATCTGTAGTGCTACAGAAAAATTGTGGGTCACAGTCTATTATGGGGTACCTGTGTGGAAAGAAGCAACCACCACTCTATTTTGTGCATCAGATGCTAAAGCATATGATACAGAGGTACATAATGTT" },
    { id: 12, organism: "Yersinia pestis", gene_name: "Plague Virulence", sequence: "TGCATGCTAGCTAGCTAGCTAGCTTGATCGATCGATCGATTTTTTTTTAAAAAAAAGCGTGCGCGCGATATATATATCGAGCTAGCTAGCTAGCTAGNNNNGCTAGCTAGCTAGCATCGATCGATTTTTTTTTAAAAAAAAGCGTGCGCGCGATATATATATCGAGCTAGCTAG" },
    { id: 13, organism: "Variola Major", gene_name: "Smallpox DNA Pol", sequence: "TTAAACCTAAAAATATATTTTTAAAATTTTTTTTCTTTTTTTAGGATCTAGAACAGGCAGCTGAACAGGCAGCCAGGGCAAAGTCTGAAGCTGAAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCGGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCGGC" },

    // --- HEWAN (ANIMALS) ---
    { id: 14, organism: "Canis Lupus", gene_name: "Olfactory Receptor", sequence: "ATGGATGGAGAGAATCACTCAGTGGTATCTGAGTTTTTGTTTCTGGGACTCACTCACTCAGGGGAGATCCAGCTCCTCCTCTTTGTGTTTTTCTCAGTGTTCTATGTGCTCAACCTGCTGGGAAATCTTCTCATCGTGCTGAGTGTGGCCTACTCCCACCTGCACACCCCCATGTA" },
    { id: 15, organism: "Felis Catus", gene_name: "Agouti Signaling", sequence: "GCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCGCCCGGCTCG" },
    { id: 16, organism: "Gallus gallus", gene_name: "Ovalbumin", sequence: "ATGGGCTCCATCGGCGCAGCAAGCATGGAATTTTGTTTTGATGTATTCAAGGAGCTCAAAGTCCACCATGCCAATGAGAACATCTTCTACTGCCCCATTGCCATCATGTCAGCTCTAGCCATGGTATACCTGGGTGCAAAAGACAGCACCCGGACACAAATAAATAAGGTTGTTCGCTTTGATAAACTTCCAGGATTCGGAGACAGTATTGAA" },
    { id: 17, organism: "Balaenoptera musculus", gene_name: "Myoglobin (Whale)", sequence: "ATGGGGCTCAGCGATGGGGAGTGGCAGCTGGTGCTGCACGTCTGGGCCAAGGTGGAGGCCGAGGCCGAGGGCCAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGCAAGGGC" },
    { id: 18, organism: "Drosophila", gene_name: "Period (Clock)", sequence: "GATCGATCGATCGCGCGCGATATATATATCGAGCTAGCTAGCTAGCTAGNNNNGCTAGCTAGCTAGCATCGATCGATTTTTTTTTAAAAAAAAGCGTGATCGATCGATCGCGCGCGATATATATATCGAGCTAGCTAGCTAGCTAGNNNNGCTAGCTAGCTAGCATCGATCGAT" },
    { id: 19, organism: "Danio rerio", gene_name: "GFP-Like (Zebra Fish)", sequence: "ATGTCTTCAAGGATGAGAGGGAGAAAGAGTGCATGCATGCATGCATGCATGCCCCCCCCCCGGGGGGGGGGTTTTTTTTTTGAGAGAGAGAGAATGTCTTCAAGGATGAGAGGGAGAAAGAGTGCATGCATGCATGCATGCATGCCCCCCCCCCGGGGGGGGGGTTTTTTTTTT" },

    // --- POP CULTURE & SCI-FI (EASTER EGGS) ---
    { id: 20, organism: "Jurassic Park Frog", gene_name: "Amphibian Gap Fill", sequence: "GATTACAGATTACAGATTACAGATTACACCCGGGTTTGGGAAATTTCCCGGGATTACAGATTACAGATTACAGATTACAGATTACACCCGGGTTTGGGAAATTTCCCGGGATTACA" },
    { id: 21, organism: "Xenomorph XX121", gene_name: "Acid Blood Enzyme", sequence: "ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT" },
    { id: 22, organism: "T-Virus (Tyrant)", gene_name: "Mutation Factor", sequence: "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTATGATGATGATGATGATGATGATGCCCCCCCCCCCCCCCCGGGGGGGGGGGGGGGGAAAATTTTTAAAATTTTCCCGGGGAAAATTTT" },
    { id: 23, organism: "Godzilla (Gojira)", gene_name: "Radiation Absorb", sequence: "RADRADRADRADRADRADGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGC" },
    { id: 24, organism: "Spider-Man", gene_name: "Recombinant Silk", sequence: "SPDRSPDRSPDRATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCA" },
    { id: 25, organism: "Umbrella Corp", gene_name: "Project Nemesis", sequence: "UMBRELLAUMBRELLAACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT" },

    // --- BAKTERI & TANAMAN ---
    { id: 26, organism: "E. Coli", gene_name: "LacZ (Beta-gal)", sequence: "ATGACCATGATTACGGATTCACTGGCCGTCGTTTTACAACGTCGTGACTGGGAAAACCCTGGCGTTACCCAACTTAATCGCCTTGCAGCACATCCCCCTTTCGCCAGCTGGCGTAATAGCGAAGAGGCCCGCACCGATCGCCCTTCCCAACAGTTGCGCAGCCTGAATGGCGAATGGCGC" },
    { id: 27, organism: "Thermus aquaticus", gene_name: "Taq Polymerase", sequence: "ATGAGGGGGATGCTGCCCCTCTTTGAGCCCAAGGGCCGGGTCCTCCTGGTGGACGGCCACCACCTGGCCTACCGCACCTTCCACGCCCTGAAGGGCCTCACCACCAGCCGGGGGGAGCCGGTGCAGGCGGTCTACGGCTTCGCCAAGAGCCTCCTCAAGGCCCTCAAGGAGGACGGGGAC" },
    { id: 28, organism: "Oryza sativa", gene_name: "Alpha-Amylase", sequence: "ATGCAGGTGCTGAACACCATGGTGAACTCCCTCAGCTCCCACCTCGACGACGTCTCGCTCCTCGTCTCCGGCGAGAGGTTCATCGAGTCCTACTGCCTCGCCCTCGCCGCCAACTCCGCCTCCGCCTCCGCCTCCGCCTCCGCCTCCGCCTCCGCCTCCGCCTCCGCCTCCGCC" },
    { id: 29, organism: "Arabidopsis", gene_name: "Flowering Locus T", sequence: "ATGCCGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAG" },

    // --- DATA SINTETIS (UNTUK TEST POLA) ---
    { id: 30, organism: "Synthetic Test 01", gene_name: "Poly-A Tail", sequence: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" },
    { id: 31, organism: "Synthetic Test 02", gene_name: "Poly-T Tail", sequence: "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT" },
    { id: 32, organism: "Synthetic Test 03", gene_name: "GC Rich Region", sequence: "GCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGC" },
    { id: 33, organism: "Synthetic Test 04", gene_name: "AT Rich Region", sequence: "ATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATAT" },
    { id: 34, organism: "Synthetic Test 05", gene_name: "Repeat Block", sequence: "AAAAACCCCCTTTTTGGGGGAAAAACCCCCTTTTTGGGGGAAAAACCCCCTTTTTGGGGGAAAAACCCCCTTTTTGGGGGAAAAACCCCCTTTTTGGGGG" },
    { id: 35, organism: "Synthetic Test 06", gene_name: "Palindrome", sequence: "GATCGATCGATCGCGCGCGATATATATATCGAGCTAGCTAGCTAGCTAGCGCGCGCGATATATATATCGAGCTAGCTAGCTAGCTAG" },
    
    // --- FILLER DATA (GENERATED) UNTUK MEMENUHI GRID ---
    { id: 36, organism: "Unknown Sample 001", gene_name: "Unidentified", sequence: "CGTAGCTAGCTGATCGATCGTAGCTGATCGATCGTAGCTGATCGATCGTAGCTGATCGATCGTAGCTGATCGATCGTAGCTGATCGATCGTAGCTGATCG" },
    { id: 37, organism: "Unknown Sample 002", gene_name: "Unidentified", sequence: "TGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCA" },
    { id: 38, organism: "Deep Sea Vent Bacteria", gene_name: "Heat Resistance", sequence: "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG" },
    { id: 39, organism: "Space Debris 4X", gene_name: "Alien Microbe", sequence: "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN" },
    { id: 40, organism: "Lab Rat #455", gene_name: "Memory Gene", sequence: "ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCG" },
    { id: 41, organism: "Fungi: Aspergillus", gene_name: "Toxin Production", sequence: "TGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTG" },
    { id: 42, organism: "Ancient Amber Mosquito", gene_name: "Preserved Blood", sequence: "GATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGATTACAGA" },
    { id: 43, organism: "Synthetic Primer F", gene_name: "PCR Control", sequence: "CTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAG" },
    { id: 44, organism: "Synthetic Primer R", gene_name: "PCR Control", sequence: "GATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATC" },
    { id: 45, organism: "Mutated Corn", gene_name: "Pest Resistance", sequence: "CGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCGCG" },
    { id: 46, organism: "Vampire Bat", gene_name: "Anticoagulant", sequence: "AAATTTCCCGGGAAATTTCCCGGGAAATTTCCCGGGAAATTTCCCGGGAAATTTCCCGGGAAATTTCCCGGGAAATTTCCCGGGAAATTTCCCGGGAAAT" },
    { id: 47, organism: "Tardigrade", gene_name: "Space Survival", sequence: "GGGGAAAATTTTGGGGAAAATTTTGGGGAAAATTTTGGGGAAAATTTTGGGGAAAATTTTGGGGAAAATTTTGGGGAAAATTTTGGGGAAAATTTTGGGG" },
    { id: 48, organism: "Area 51 Sample", gene_name: "Classified", sequence: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" },
    { id: 49, organism: "Chernobyl Fungi", gene_name: "Rad-Eater", sequence: "RADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRADRAD" },
    { id: 50, organism: "Clone Trooper", gene_name: "Obedience", sequence: "CTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCT" },
    { id: 51, organism: "Matrix Code", gene_name: "Digital DNA", sequence: "1010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010" },
    { id: 52, organism: "Proto-Molecule", gene_name: "Expanse", sequence: "BLUEMATTERBLUEMATTERBLUEMATTERBLUEMATTERBLUEMATTERBLUEMATTERBLUEMATTERBLUEMATTERBLUEMATTERBLUEMATTER" },
    { id: 53, organism: "Na'vi (Pandora)", gene_name: "Neural Queue", sequence: "CATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATC" },
    { id: 54, organism: "Cyberpunk Implant", gene_name: "Bio-Ware", sequence: "CHROMECHROMECHROMECHROMECHROMECHROMECHROMECHROMECHROMECHROMECHROMECHROMECHROMECHROMECHROMECHROMECHROME" },
    { id: 55, organism: "Zombie Patient Zero", gene_name: "Rage Virus", sequence: "RAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGERAGE" },
    { id: 56, organism: "Mimic Octopus", gene_name: "Camouflage", sequence: "TGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCA" },
    { id: 57, organism: "Platypus", gene_name: "Venom Spur", sequence: "POISONPOISONPOISONPOISONPOISONPOISONPOISONPOISONPOISONPOISONPOISONPOISONPOISONPOISONPOISONPOISONPOISON" },
    { id: 58, organism: "Electric Eel", gene_name: "Shock Gen", sequence: "VOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLTVOLT" },
    { id: 59, organism: "Axolotl", gene_name: "Regeneration", sequence: "GROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROW" },
    { id: 60, organism: "Final Boss", gene_name: "Destruction", sequence: "ENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDENDEND" }
];